### ISSUE TITLE
Cypress fails on CI (github action)

### ISSUE THREAD

**Issue by sergivillar** [remix-run/indie-stack#103]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Create a new project, deploy it with the github action, it will fails as it seems there's a bug with the latests NPM version.

This is the error

` npm ERR! 'npm ci' can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with 'npm install' before continuing.`

FYI: I fix this issue changing the node version of the Cypress state to `node-version: 16.10.0` (last v7 npm version) and it works.

### Expected Behavior

Not fail in the cypress step on github action.

### Actual Behavior

Cypress step of the build fails.

**Comment by MichaelDeBoey** [comment]
Will probably be fixed by #102

**Comment by MichaelDeBoey** [comment]
Closed by #102

**Comment by AsaAyers** [comment]
I don't think this fully fixed it 😢 I just created a new project by running `npx create-remix --template remix-run/indie-stack` and following the readme. `npm ci` works locally but fails on CI.

![image](https://user-images.githubusercontent.com/324999/172977435-97b50dfe-8a8c-4cb3-a912-b8389518ca6a.png)

**Comment by AsaAyers** [comment]
This got me past that `npm ci` error.

```diff
index d01b1b0..a45574c 100644
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -100,7 +100,7 @@ jobs:
       - name: 📥 Download deps
         uses: bahmutov/npm-install@v1
         with:
-          useLockFile: false
+          useLockFile: true
 
       - name: 🛠 Setup Database
         run: npx prisma migrate reset --force
```

**Comment by mcansh** [comment]
ah yep, the first run won't have a lock file until the deps are installed due to https://github.com/remix-run/indie-stack/pull/79, personally i think it's fine to have them by default and if someone wants to use a diff package manager, they'll know what to do

**Comment by machour** [comment]
@mcansh Could we add some output to the CI about this to avoid confusing users?

**Comment by mcansh** [comment]
something like? I'm not sure this is better than just having one by default as we still use `npm` in the Dockerfile

```yaml
- name: Check for lockfile
  run: |
    FILE=package-lock.json
    if [ ! -f "$FILE" ]; then
      echo "$FILE does not exist. Please run `npm install` before continuing"
      exit 1
    fi
```

**Comment by AsaAyers** [comment]
I did "npm install" first. I did have a package-lock.json.

The step that's failing is complaining the lock file is out of sync. I was
able to fix that by adjusting an earlier step and telling it to use the
lock file to check out the dependencies.

I think by explicitly disabling the lock file, it would check out different
versions of packages and then that cuses "npm ci" to complain about them
being out of sync.

**Comment by mcansh** [comment]
> I think by explicitly disabling the lock file, it would check out different versions of packages and then that causes "npm ci" to complain about them being out of sync.

something is definitely up, but i don't think that's it as opting out of the lock file uses `npm install` and not `npm ci`

**Comment by mcansh** [comment]
interesting, i just created a new app and the cypress job passed https://github.com/mcansh/grunge-stack-test/runs/6970287593?check_suite_focus=true

**Comment by machour** [comment]
Closing this issue as no response was provided.
Feel free to re-open it if it's still a problem.
