### ISSUE TITLE
npm run setup fails for indie-stack template

### ISSUE THREAD

**Issue by kevin-kabore** [remix-run/indie-stack#119]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

run `npx create-remix@latest --template remix-run/indie-stack`
? Where would you like to create your app? `blog-tutorial`
? TypeScript or JavaScript? `TypeScript`
? Do you want me to run `npm install`? `Yes`

### Expected Behavior

It should successfully complete the setup as well as `npm run dev` locally.

### Actual Behavior

```
✔ Generated Prisma Client (4.0.0 | library) to ./node_modules/@prisma/client in 389ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Error: Get Config: Schema parsing - Error while interacting with query-engine-node-api library
Error code: P1012
error: Error validating datasource `db`: the URL must start with the protocol `file:`.
  -->  schema.prisma:3
   | 
 2 |   provider = "sqlite"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1

Prisma CLI Version : 4.0.0
🚨 Oops, remix.init failed

Command failed: npm run setup
```

**Comment by kevin-kabore** [comment]
Worth noting:
- This works when run in Gitpod per the prerequisites in the docs
- Updating the `DATABASE_URL` does not resolve the issue
- doesn't seem related to using a `seed.js` instead of `seed.ts` for the Typescript template

**Comment by kentcdodds** [comment]
I just tried this myself and couldn't reproduce.

**Comment by kevin-kabore** [comment]
Got it resolved on my end thank you. Probably nothing, so I'll update the docs if I run into this issue again. Thanks for checking this out kent!
