### ISSUE TITLE
Deploy fly.io error, app runs fine locally

### ISSUE THREAD

**Issue by SangeetAgarwal** [remix-run/indie-stack#132]
### Have you experienced this bug with the latest version of the template?

Yes, repo at https://github.com/SangeetAgarwal/bitoflearning

### Steps to Reproduce

If you were to clone https://github.com/SangeetAgarwal/bitoflearning then you'll see it runs just fine with either the `npm run dev` or `npm run build` and `npm start`.

But when I attempt to deploy to fly.io then at https://bitoflearning-9a57.fly.dev/ then I get the following error in the deploy stage 

> 2022-07-27T12:51:34Z   [info]    at /myapp/build/index.js:615:111
> 2022-07-27T12:51:34Z   [info]    at getAllFilesRecursively (/myapp/build/index.js:615:623)
> 2022-07-27T12:51:34Z   [info]    at getAllFilesFrontMatter (/myapp/build/index.js:634:85)
> 2022-07-27T12:51:34Z   [info]    at loader5 (/myapp/build/index.js:738:43)
> 2022-07-27T12:51:34Z   [info]    at Object.callRouteLoader (/myapp/node_modules/@remix-run/server-runtime/dist/data.js:77:20)
> 2022-07-27T12:51:34Z   [info]    at /myapp/node_modules/@remix-run/server-runtime/dist/server.js:261:113
> 2022-07-27T12:51:34Z   [info]    at Array.map (<anonymous>)
> 2022-07-27T12:51:34Z   [info]HEAD / 500 - - 4.089 ms
> 2022-07-27T12:51:34Z   [info]healthcheck  {

### Expected Behavior

app should run and show the landing page at [https://bitoflearning-9a57.fly.dev/](https://bitoflearning-9a57.fly.dev/)

### Actual Behavior

But when I attempt to deploy to fly.io then at [https://bitoflearning-9a57.fly.dev/](https://bitoflearning-9a57.fly.dev) then I get the following error in the deploy stage 

> 2022-07-27T12:51:34Z   [info]    at /myapp/build/index.js:615:111
> 2022-07-27T12:51:34Z   [info]    at getAllFilesRecursively (/myapp/build/index.js:615:623)
> 2022-07-27T12:51:34Z   [info]    at getAllFilesFrontMatter (/myapp/build/index.js:634:85)
> 2022-07-27T12:51:34Z   [info]    at loader5 (/myapp/build/index.js:738:43)
> 2022-07-27T12:51:34Z   [info]    at Object.callRouteLoader (/myapp/node_modules/@remix-run/server-runtime/dist/data.js:77:20)
> 2022-07-27T12:51:34Z   [info]    at /myapp/node_modules/@remix-run/server-runtime/dist/server.js:261:113
> 2022-07-27T12:51:34Z   [info]    at Array.map (<anonymous>)
> 2022-07-27T12:51:34Z   [info]HEAD / 500 - - 4.089 ms
> 2022-07-27T12:51:34Z   [info]healthcheck  {

**Comment by SangeetAgarwal** [comment]
I see a similar issue that folks were having https://github.com/remix-run/remix/issues/564 but in my case all works just fine locally and only once I deploy to fly.io do I get a similar error

**Comment by mcansh** [comment]
the app directory isn't copied to the final docker image https://github.com/SangeetAgarwal/bitoflearning/blob/main/Dockerfile#L52-L59

```diff
COPY --from=production-deps /myapp/node_modules /myapp/node_modules
COPY --from=build /myapp/node_modules/.prisma /myapp/node_modules/.prisma

COPY --from=build /myapp/build /myapp/build
COPY --from=build /myapp/public /myapp/public
COPY --from=build /myapp/package.json /myapp/package.json
COPY --from=build /myapp/start.sh /myapp/start.sh
COPY --from=build /myapp/prisma /myapp/prisma
+ COPY --from=build /myapp/app/data /myapp/app/data
```

![image](https://user-images.githubusercontent.com/11698668/181279131-95aabe01-e787-452d-8138-6346c6d564b6.jpeg)

**Comment by mcansh** [comment]
refreshing on a page shows esbuild appears to be missing ![image](https://user-images.githubusercontent.com/11698668/181298576-3d0635ab-56da-4df0-9e30-a73999936811.png)

**Comment by SangeetAgarwal** [comment]
@mcansh working nicely at https://bitoflearning-9a57.fly.dev/blogs/new-features-in-v1.
Seems along with the `esbuild` dependency, I had to add a few more directories to the final docker image 
```
COPY --from=build /myapp/app/components /myapp/app/components
COPY --from=build /myapp/app/layouts /myapp/app/layouts
COPY --from=build /myapp/app/lib /myapp/app/lib
```
Thank you for the time, much appreciated, have been working on translating (still in an early stage) https://github.com/timlrx/tailwind-nextjs-starter-blog to [remix ](https://github.com/SangeetAgarwal/bitoflearning)& was working on this project since late Friday 7/22 almost non-stop as I come up to speed w/remix. I'm beginning to understand remix a bit better so again thanks.
