### ISSUE TITLE
JS version: Warning: Expected server HTML to contain a matching <link> in <body>.

### ISSUE THREAD

**Issue by karimhossenbux** [remix-run/indie-stack#135]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

- npx create-remix@latest (indie stack, javascript version)
- npm run dev

### Expected Behavior

Expected no error while opening localhost:3000

### Actual Behavior

Getting a bunch of error in console:
<img width="1104" alt="Screenshot 2022-08-12 at 22 57 22" src="https://user-images.githubusercontent.com/584224/184444385-000a8b64-8532-4ca1-a7cf-7f76a7ecee90.png">

**Comment by machour** [comment]
Can you try without your browser extensions ? (incognito mode)
See also https://remix.run/docs/en/v1/pages/gotchas#browser-extensions-injecting-code

**Comment by karimhossenbux** [comment]
Damn, it was LastPass :(
Sorry about that, closing the issue.
Thanks @machour!
