### ISSUE TITLE
Remix.init fails when choosing TypeScript

### ISSUE THREAD

**Issue by milamer** [remix-run/indie-stack#136]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

? What type of app do you want to create? **A pre-configured stack ready for production**
? Which Stack do you want? (Learn more about these stacks: 'https://remix.run/stacks') **Indie**
? TypeScript or JavaScript? **TypeScript**
? Do you want me to run `npm install`? **Yes**

💿 Running remix.init script
🚨 Oops, remix.init failed

[index.js:readFileIfNotTypeScript](https://github.com/remix-run/indie-stack/blob/7c23ab436bb2a42fec5a126d14ee7151e6ac9e85/remix.init/index.js#L49) seems to have wrong brackets

Current:
```ts
  (isTypeScript ? Promise.resolve() : fs.readFile(filePath, "utf-8")).then(
    parseFunction
  );
```
Expected
```ts
  (isTypeScript ? Promise.resolve() : fs.readFile(filePath, "utf-8").then(
    parseFunction
  ));
```

### Expected Behavior

remix.init should run successfully

### Actual Behavior

remix.init fails

**Comment by dario-piotrowicz** [comment]
Hi there, I am running into the same issue, but the error looks different:

![Screenshot at 2022-08-12 23-12-34](https://user-images.githubusercontent.com/61631103/184451425-1ccfc099-8fd6-4429-ae08-8be0c5b7b3d0.png)

Is this related or a different issue?

**Comment by MichaelDeBoey** [comment]
#138 is addressing some issues with both JS + TS version
