### ISSUE TITLE
create-remix cli run into error when trying to run `npx remix init` 

### ISSUE THREAD

**Issue by Senbonzakura1234** [remix-run/indie-stack#139]
### What version of Remix are you using?

1.6.7

### Steps to Reproduce

Run create-remix cli with options below:

![image](https://user-images.githubusercontent.com/43206347/184470123-99a242ee-1129-42db-9aed-4efb03951808.png)
****

### Expected Behavior

The cli run `remix.init` script successfully

### Actual Behavior

The `remix.init` script run into error

`🚨 Oops, remix.init failed`
`Cannot read properties of undefined (reading 'length')`

**Comment by MichaelDeBoey** [comment]
This will be fixed by #138
