### ISSUE TITLE
Oops, remix.init failed - no such file or directory, open '/cypress/support/commands.js'

### ISSUE THREAD

**Issue by kevinbailey25** [remix-run/indie-stack#143]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. run `npx create-remix@latest`
2. name the app
3. create a pre-configured stack
4. select `Indie`
5. select `TypeScript`
6. select `Yes` to have it npm install.

Windows 10
Node 16.16.0
npm 8.15.1

### Expected Behavior

`remix.init` shouldn't fail

### Actual Behavior

![image](https://user-images.githubusercontent.com/36492257/184678422-4f469690-9203-4258-af41-44d460f522a6.png)

**Comment by danrocha** [comment]
I am also having issues, but for me the file that is missing is:

`/cypress/support/commands.js`

**Comment by kevinbailey25** [comment]
I just ran this again and got `\cypress\support\commands.js` insted of the `delete-user.js`

**Comment by onoj** [comment]
I've also seen the same behaviour described above, delete-user.js first, and commands.js on subsequent runs.

macos 12.5
node 16.16
npm 8.11


<img width="1040" alt="Screenshot 2022-08-15 at 18 22 19" src="https://user-images.githubusercontent.com/54250/184684452-5d97234f-05fb-4652-8db8-5b1be1f2cc01.png">
<img width="1040" alt="Screenshot 2022-08-15 at 18 23 11" src="https://user-images.githubusercontent.com/54250/184684463-dc68baf7-c154-40d6-b687-53c8e5d77f35.png">

**Comment by Guria** [comment]
There is a typo in init script. I am preping a fix and a workaround

**Comment by Guria** [comment]
So to workaround a problem for now if you use Typescript:
Decline offer to install dependencies.
Edit init script like this: https://github.com/remix-run/indie-stack/compare/main...Guria:indie-stack:patch-1
Run:
```sh
npm i
npx remix init
```

**Comment by MichaelDeBoey** [comment]
This will be fixed by #144
