### ISSUE TITLE
Template is not working in Firefox

### ISSUE THREAD

**Issue by Guria** [remix-run/indie-stack#145]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

* init template
* npm run dev
* open http://localhost:3000 in Firefox browser

### Expected Behavior

![image](https://user-images.githubusercontent.com/36270/184700221-af9e7cae-0c26-46d5-819e-abc959d9b354.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/36270/184700192-dfa2581a-b84c-485e-886b-5a2676efbb30.png)

**Comment by Guria** [comment]
No visible errors could be found in console.

**Comment by mikewheaton** [comment]
Everything looks good for me in Firefox on a fresh install. It looks like images aren't loading for you. If you look at the network tab, what's showing for the image requests? Could you try loading it in a private browser, in case this is related to an ad blocker or similar?

**Comment by Guria** [comment]
I don't know what have changed but today is ok. But I even didn't reboot my laptop. Will close issue for now and let me know if it repeats by any condition.
