### ISSUE TITLE
Unable to run latest IndieStack (JS) on Windows

### ISSUE THREAD

**Issue by chelseachampions** [remix-run/indie-stack#146]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Windows 10 Pro 
NPM: '8.5.4'
Node: '16.16.0'
JS/TS: JS

npx create-remix --template remix-run/indie-stack
Select 'JavaScript'
cd <new folder>
npm run dev
hit localhost:3000
app crashes (see errors in Actual Behavior)

### Expected Behavior

App remains operational

### Actual Behavior

App errors before loading:
![image](https://user-images.githubusercontent.com/43727271/184892642-7b9a4d6a-5184-4819-99d1-9df72edcf323.png)
Console:
![image](https://user-images.githubusercontent.com/43727271/184892559-1ac9d60b-b0ae-45cb-b227-f319f310cd19.png)

**Comment by maxbaun** [comment]
I am seeing the same issue as well on Windows 10
