### ISSUE TITLE
Expected server HTML to contain a matching <head> in <html> with a Failed Hydration Exception

### ISSUE THREAD

**Issue by ipenywis** [remix-run/indie-stack#148]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

- Follow the steps to create a project from the template
- Run `npm run dev` or `yarn dev`
- Try to Login/Register
- Open Console
- Notice errors preventing hydration and causing exceptions

### Expected Behavior

The template once used to generate a new project it shouldn't have hydration errors for beginners to get started

### Actual Behavior

When starting the app in development mode, it shows a warning
`Warning: Expected server HTML to contain a matching <head> in <html>.`
Followed by Hydration exceptions
`Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.`

Operating System: macOS

Here is the screenshot from the console
![image](https://user-images.githubusercontent.com/13965825/185988075-b82c6f38-0307-4aea-b7a3-fa74d19542dc.png)

**Comment by ipenywis** [comment]
Sorry! It looks like it's a chrome extension causing the issue.
Had to remove this https://chrome.google.com/webstore/detail/mockman-mock-apis/bigfgeehfoenaimkoohnokeeideaomnd

What I learned was always test SSR apps in incognito mode first 🙃

**Comment by designbyadrian** [comment]
Removing an extension isn't a solution, as you can't expect all your users to do so.
