### ISSUE TITLE
"Invariant Failed" on `npm run start`

### ISSUE THREAD

**Issue by alifhaider** [remix-run/indie-stack#170]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

I am getting this error on `npm run start`. I am not so sure why I am getting this error. The `dev` server works fine. But with `npm start` I am getting this error.

```
hotel-rental/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10
        throw new Error(prefix);
              ^
Error: Invariant failed
    at invariant (myapp/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:10:15)
    at init (myapp/build/index.js:43:39)
    at Object.<anonymous> (myapp/build/index.js:48:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous>

```
    

### Expected Behavior

I was trying to run `cypress` test with GitHub action. I did everything as per the documentation. But while adding the `--record --key` the script fails with the error. 

The consoled message was `Database URL is required`
But I don't know where I didn't put my database URL. 

### Actual Behavior

App should also run just like in dev it is running.

**Comment by MichaelDeBoey** [comment]
It sounds like you didn't setup environment variables on you production server

**Comment by alifhaider** [comment]
I had to change my `start:mocks` script in `package.json` file to make it work.
It was: 
```
"start:mocks": "binode --require ./mocks -- @remix-run/serve:remix-serve build",
```
Changed to: 
```
"start:mocks": "binode --require ./mocks --require ./node_modules/dotenv/config -- @remix-run/serve:remix-serve build",
```

**Comment by FranciscoKloganB** [comment]
I have this issue on `start:mocks` as well, but only on the Cypress step of GitHub actions.

Locally, I can get this to work, either by having the environment variables required for the project on my `.zshrc`, and `.envrc` or loading them with `dotenv` dev dependency as suggested above. When I drop any of these approaches, the `start:mock` command fails, as expected!

However, I can't figure out how to make this work on the pipeline on job step `name: ⚫️ Cypress`; I already added all of my environment variables to `GitHub secrets`. :)

 My `fly.io` deployments are also working fine. :ok_hand:
