### ISSUE TITLE
Broken link in `mocks/README.md`

### ISSUE THREAD

**Issue by runofthemill** [remix-run/indie-stack#176]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Click the link link in `mocks/README.md` 404s:

> For an extensive example, see the [source code for kentcdodds.com](https://github.com/kentcdodds/kentcdodds.com/blob/main/mocks/start.ts)

### Expected Behavior

The link should work.

### Actual Behavior

It doesn't :(

Maybe it's meant to point to https://github.com/kentcdodds/kentcdodds.com/blob/main/mocks/index.ts?

**Comment by MichaelDeBoey** [comment]
This was changed in https://github.com/kentcdodds/kentcdodds.com/commit/00157a602bd6ab48b8b173a15c2c055156ddfa2b

**Comment by runofthemill** [comment]
thanks so much @MichaelDeBoey - I looked for that change but missed it cause GH only shows the file name change in the right side of the diff and I was looking at the file tree on the left 🙈 
<img width="716" alt="Screen Shot 2022-11-28 at 10 15 19 AM" src="https://user-images.githubusercontent.com/8418440/204350828-14f979e1-4377-439a-a1b3-ed0fc4801ffd.png">
