### ISSUE TITLE
Indie stack does not load `.env.example`, causing app to crash

### ISSUE THREAD

**Issue by stephenjbradshaw** [remix-run/indie-stack#179]
### What version of Remix are you using?

1.7.6

### Steps to Reproduce

Node version: 18.12.1
NPM version: 8.12.2
Intel mac, macOS Ventura 13.0

1. Following the [quickstart guide](https://remix.run/docs/en/v1/tutorials/blog) locally:
```
npx create-remix@latest --template remix-run/indie-stack blog-tutorial
? TypeScript or JavaScript? TypeScript
? Do you want me to run `npm install`? Yes
```
2. Run `npm run dev`
3. Navigate to `localhost:3000`

### Expected Behavior

Loads indie stack demo app without error

### Actual Behavior

Error in console on navigating to `localhost`

```
/Users/stephenbradshaw/blog-tutorial/node_modules/@prisma/client/runtime/index.js:30355
          throw new PrismaClientInitializationError(error2.message, this.config.clientVersion, error2.error_code);
                ^
Error: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   | 
 2 |   provider = "sqlite"
 3 |   url      = env("DATABASE_URL")
   | 
```

**Cause**
it seems that `.env` files are not being loaded

**Reasoning**
If you inject the contents of `.env.example` directly into the the `dev` script in `package.json` and restart the dev server, there is no error and the demo app works as expected:

`"dev":  "DATABASE_URL=file:./data.db?connection_limit=1 SESSION_SECRET=super-duper-s3cret run-p dev:*"`

Renaming the `.env.example` file to `.env.dev` or similar does not help. For some reason it seems `.env` files are not being loaded at all 🤷

**Comment by MichaelDeBoey** [comment]
This is because your `remix.init` script didn't run.
`npx remix init` should fix it

**Comment by stephenjbradshaw** [comment]
Thanks, I can confirm `npx remix init` fixed this. I think what happened is that the `npm install` failed the first time due to slow connection, and I ran it manually, meaning the init script didn't run.

I don't think it's clear for a new user (at least a dozy one like me 😉 ) that the init script is run after `npm install`.  I have two DX suggestions:

1. Perhaps it might be clearer if the CLI prompt was:
``Do you want me to run `npm install` and the remix.init script`?``

    This way the dev knows they need to run the script manually if there is a failure.

2. In the stack README it says:
`This step [npx remix init] only applies if you've opted out of having the CLI install dependencies for you`

    This is also a little confusing – I had not opted out, so I assumed that the script had run.

    Maybe this would be clearer:
    `This step only applies if you've opted out of having the CLI install dependencies for you, or there was an error during the install`

Would be happy to raise a PR with these changes.
