### ISSUE TITLE
Dev Server after setup prints tons of GET /_next/webpack-hmr 404 messages

### ISSUE THREAD

**Issue by phifa** [remix-run/indie-stack#181]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

`npx create-remix@latest --template remix-run/indie-stack`
`rm -rf package-lock.json node_modules`
`yarn`
`yarn setup`
`yarn dev`

### Expected Behavior

normal running dev server

### Actual Behavior

```

Rebuilding...
Loading environment variables from .env

Done in 132ms.
Remix App Server started at http://localhost:3000 (http://192.168.1.31:3000)
GET /_next/webpack-hmr 404 - - 73.516 ms
GET /_next/webpack-hmr 404 - - 11.488 ms
GET /_next/webpack-hmr 404 - - 7.718 ms
GET /_next/webpack-hmr 404 - - 7.193 ms
GET /_next/webpack-hmr 404 - - 3.930 ms
GET /_next/webpack-hmr 404 - - 9.169 ms
GET /_next/webpack-hmr 404 - - 8.235 ms
GET /_next/webpack-hmr 404 - - 8.997 ms
GET /_next/webpack-hmr 404 - - 5.725 ms
GET /_next/webpack-hmr 404 - - 9.856 ms
GET /_next/webpack-hmr 404 - - 6.102 ms
GET /_next/webpack-hmr 404 - - 8.370 ms
GET /_next/webpack-hmr 404 - - 7.890 ms
...
```

**Comment by machour** [comment]
This is not a remix issue, you probably have a browser tab open on a next app that is generating those calls.

**Comment by phifa** [comment]
why everybody has to use port 3000 🤦🏼. you are right, sorry about that 💚

**Comment by AmmarYousaf6** [comment]
You can switch to another port to resolve the issue or kill the port "npx kill-port {{port}}".

**Comment by AmmarYousafFA** [comment]
You can Switch to another port

**Comment by Krovikan-Vamp** [comment]
I actually had this issue recently and it was popping up because the reverse proxy (nginx) config was not supporting websockets (which lets HMR work). Enabling Websocket Support in nginx fixed the issue right away.

Hope this helps someone!
