### ISSUE TITLE
Expected server HTML to contain a matching <head> in <html>

### ISSUE THREAD

**Issue by OnlyC** [remix-run/indie-stack#184]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

- npx create-remix@latest --template remix-run/indie-stack
- npm run dev

### Expected Behavior

No errors

### Actual Behavior

![image](https://user-images.githubusercontent.com/1250580/208474503-f1ab1427-85af-47b8-bf69-4c53e758fa3d.png)

**Comment by OnlyC** [comment]
Found the fix:
https://remix.run/docs/en/v1/pages/gotchas#browser-extensions-injecting-code

**Comment by designbyadrian** [comment]
> Found the fix: https://remix.run/docs/en/v1/pages/gotchas#browser-extensions-injecting-code

There is no fix mentioned in the link.

**Comment by pixeleate** [comment]
@designbyadrian the fix is to open the app in incognito mode, yes I know, I think the same this is not a fix, but it's what they suggested.

**Comment by danielbyun** [comment]
Ran into issue today and found the plugin that was causing this issue. The fix is as @OnlyC 's url provided.

**Comment by bokaroto** [comment]
hydration fails due to extensions that you have in your browser, it has nothing to do with the remix, it's a problem in React.
Because they inject extensions into pages , insert their own code, and then when rendering to the server and then to the client It's different and that's why it throws errors. 
Ignore it or use the incognito tab.

**Comment by YuraGB** [comment]
> hydration fails due to extensions that you have in your browser, it has nothing to do with the remix, it's a problem in React. Because they inject extensions into pages , insert their own code, and then when rendering to the server and then to the client It's different and that's why it throws errors. Ignore it or use the incognito tab.

You are right

**Comment by mahmoudmoravej** [comment]
Mine was becuase of "Apollo Client Dev tools" extension. Disabling it solved as suggessted.

**Comment by Guteres007** [comment]
> Mine was becuase of "Apollo Client Dev tools" extension. Disabling it solved as suggessted.

Yes, work for me in V2

**Comment by deadcoder0904** [comment]
> @designbyadrian the fix is to open the app in incognito mode, yes I know, I think the same this is not a fix, but it's what they suggested.

solved it for me :)

**Comment by designbyadrian** [comment]
> > @designbyadrian the fix is to open the app in incognito mode, yes I know, I think the same this is not a fix, but it's what they suggested.
> 
> 
> 
> solved it for me :)

It won't solve it for every visitor to your website.

**Comment by deadcoder0904** [comment]
> It won't solve it for every visitor to your website.

well, only developers like to open the console.

and there are many high-profile production websites that have consoles filled with red-wedding :)

**Comment by Disorrder** [comment]
Fixed by restricting allowed sites list for my specific extension not related to react

**Comment by deadcoder0904** [comment]
@Disorrder how did you do that? i tried googling for hacks like that but nothing worked lol.

**Comment by fzn0x** [comment]
@deadcoder0904 I think modify the `manifest.json`

or use this code for manifest 2

```js
chrome.browserAction.onClicked.addListener(function(tab) {
    if(!tab.url || !tab.url.startsWith('http')){
        return;
    }

    // do stuff
});
```

**Comment by designbyadrian** [comment]
> > It won't solve it for every visitor to your website.
> 
> well, only developers like to open the console.
> 
> and there are many high-profile production websites that have consoles filled with red-wedding :)

The problem is that this error can cause blocked renders, leading to empty pages or missing styles. It's not simply the issue of text inside the console.

**Comment by ivo-kalendar** [comment]
> > > It won't solve it for every visitor to your website.
> > 
> > 
> > well, only developers like to open the console.
> > and there are many high-profile production websites that have consoles filled with red-wedding :)
> 
> The problem is that this error can cause blocked renders, leading to empty pages or missing styles. It's not simply the issue of text inside the console. You can't force users to disable extensions or view in incognito mode.
> 
> The real solution is to use a certain version of React that has a fix. Apparently, version 19 rc has it. Previously, it was the canary version of 18.3.0: 18.3.0-canary-a870b2d54-20240314
> 
> Set the exact version and overrides in package.json
> 
> ```
> "dependencies": {
>     "react": "18.3.0-canary-a870b2d54-20240314",
>     "react-dom": "18.3.0-canary-a870b2d54-20240314",
>   ...
> },
> "overrides": {
>     "react": "18.3.0-canary-a870b2d54-20240314",
>     "react-dom": "18.3.0-canary-a870b2d54-20240314"
>   },
> }
> ```

@designbyadrian this works fine. I don't see the usual error and the production console is clean, but now i have another error only in development: 
`Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "" Client: "\n/* /app/tailwind.css */\n/*\n! tailwindcss v3.4.4 | MIT License | https://tailwindcss.com\n*//*\n1. Prevent padding and border from affecting element width.....`
I'm using the latest: 
`npx create-remix@latest --template remix-run/remix/templates/express`

**Comment by ARBS23** [comment]
Removing `Dark Mode v0.5.1` **Chrome extension** solved the issue

**Comment by Mati365** [comment]
Disabling **Bitwarden** extension on Firefox solved the issue
