### ISSUE TITLE
Logout directly by hiting http://localhost:3000/logout should remove the cookie stored in the browser

### ISSUE THREAD

**Issue by kayode-adechinan** [remix-run/indie-stack#185]
### What version of Remix are you using?

1.9.0

### Steps to Reproduce

Setup the indie stack
- https://github.com/remix-run/indie-stack
- npx create-remix@latest --template remix-run/indie-stack
- npm run dev
- http://localhost:3000/join
- http://localhost:3000/logout

### Expected Behavior

when i hit 

http://localhost:3000/logout  url directly in a browser, i also expect the logout function to also remove  the cookie stored in my cookie storage that i can see by open up the browser storage tab

### Actual Behavior

The cookie is not removed

![Screenshot from 2022-12-22 12-18-54](https://user-images.githubusercontent.com/28058096/209133214-4f246551-6887-4ba4-9c96-a402f2acb5f8.png)

when hiting directly http://localhost:3000/logout

**Comment by machour** [comment]
Hitting directly /logout shouldn't log you out, as it is bad practice.

If you do that, I could put an image on my website like this:
  `<img src="https://yourwebsite/logout" />`
and have all your users logged out from your website when they visit mine.
Or a prefetch on your own website could do that.
You don't want that.


Logout should only happens with POST (action) and this is how this stack is implementing it:
   https://github.com/remix-run/indie-stack/blob/main/app/routes/logout.tsx

**Comment by kayode-adechinan** [comment]
I understand much better. Thanks for the clarifications. I appreciate

**Comment by dvnrsn** [comment]
I don't think it's working in the stack any more. The linked [logout.tsx](https://github.com/remix-run/indie-stack/blob/main/app/routes/logout.tsx) does have an action but the route automatically redirects. I'm assuming this is not desired
