### ISSUE TITLE
 Build Failed - buildx failed with: error: failed to solve: unexpected status: 404 Not Found

### ISSUE THREAD

**Issue by varakumar1105** [remix-run/indie-stack#19]
![image](https://user-images.githubusercontent.com/16848669/159050207-cbb7478c-c1ef-4bb6-b417-aae527947355.png)

**Comment by varakumar1105** [comment]
@kentcdodds 

I followed the same procedure in the video https://www.youtube.com/watch?v=1uebyGwAGvg

The build is failing. Could you please let me know what the problem might be?

Thanks in advance

![image](https://user-images.githubusercontent.com/16848669/159051715-18d365cd-96b3-4b96-bc4c-09026fd74b49.png)

**Comment by varakumar1105** [comment]
> Hi @varakumar1105,
> 
> Did you create the fly app first? Do you have a link to the github repo?

Yes. FLY_API_TOKEN has also been added.

https://github.com/varakumar1105/remix-indie-stack-app

**Comment by kentcdodds** [comment]
Glad you got it working. Yeah, you want to make sure that you follow the instructions in your own README rather than the repo README. Maybe we should make a note of this or something 🤔
