### ISSUE TITLE
Collaborator init script is missing

### ISSUE THREAD

**Issue by sfrieson** [remix-run/indie-stack#192]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. Clone an existing Remix/Indie Stack project
2. Run `npx remix init`
3. Run `npm run setup`

### Expected Behavior

Setup script should complete

### Actual Behavior

Setup results in an environment variable error.

```
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   | 
 2 |   provider = "sqlite"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
[Context: getConfig]
```

---
This seems to be because the `remix.init` directory is removed after it was run by the repo creator.

To resolve, I got the directory from the template repo, and added it to my cloned repo.

This also resulted in an error...
```
[Error: 🚨 Oops, remix.init failed

ENOENT: no such file or directory, stat '/Users/stevenfrieson/code/lists/.github/dependabot.yml'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/Users/sfrieson/code/lists/.github/dependabot.yml'
}
```

...but the .env file was created, so I continued successfully with `npm run setup`.

**Comment by MichaelDeBoey** [comment]
@sfrieson You should create new project by running

```sh
npx create-remix@latest --template remix-run/indie-stack
```

Not by cloning the repo

**Comment by sfrieson** [comment]
> You should create new project by running

@MichaelDeBoey I am collaborating with someone who has already run the command you supplied.

My issue is when I clone their repo to start working with them. This is not about starting a fresh project but rather joining an existing project that originally used the `npx` command.

**Comment by MichaelDeBoey** [comment]
@sfrieson It is advised to put an `.env.example`  file in your repo in that case & copy it over to `.env` file when working on it locally
