### ISSUE TITLE
NPM run dev failing

### ISSUE THREAD

**Issue by hamishakl** [remix-run/indie-stack#20]
I keep getting the following when I run 'NPM run dev' and I can't seem to figure out the problem.  Do you have any suggestions? thank you so much 

> dev:css
> npm run generate:css -- --watch

> dev:remix
> node --require ./mocks ./node_modules/.bin/remix dev

🔶 Mock server running
SyntaxError: missing ) after argument list

**Comment by hamishakl** [comment]
![image](https://user-images.githubusercontent.com/60582221/159140137-7558ce01-20fa-488d-9c94-6058eead35a9.png)

**Comment by hamishakl** [comment]
npm run validate output

![image](https://user-images.githubusercontent.com/60582221/159140154-6049f05c-7431-437e-95d0-22a5cc66bcdf.png)

**Comment by hamishakl** [comment]
Changed the following script in the package.json file

    "dev:remix": "node --require ./mocks ./node_modules/.bin/remix dev",
 to     "dev:remix": "remix dev",

**Comment by moishinetzer** [comment]
I have done the above and still have this error showing up...

**Comment by mickasmt** [comment]
Hey @kentcdodds ! I just did an install after your new commit.
The installation is good but when I use the "npm run dev" command I always get the following error:
> ![image](https://user-images.githubusercontent.com/60582221/159140137-7558ce01-20fa-488d-9c94-6058eead35a9.png)

I think we should really see what's wrong with "mock server" and with the syntax error.

**Comment by oddig** [comment]
I had the same issue on windows, fixed by changing the dev:remix script:
`"dev:remix": "node --require ./mocks ./node_modules/@remix-run/dev/cli.js"`

**Comment by mickasmt** [comment]
@oddig thanks ! It works now for me.

**Comment by moishinetzer** [comment]
npm run validate still doesn't work however even with the above fix...

**Comment by oddig** [comment]
Unfortunately running on a windows machine does not always work at first glance 😭 .
Try this, it worked for me at least:
`"start:mocks": "node --require ./mocks ./node_modules/@remix-run/serve/cli.js build"`

**Comment by moishinetzer** [comment]
The above works for me! thanks @oddig

**Comment by kentcdodds** [comment]
Could you try the latest version? I'm pretty sure this is resolved now.

**Comment by oddig** [comment]
Unfortunately it does not work.
![image](https://user-images.githubusercontent.com/432917/159592705-0616ca10-64d8-48c8-b4f4-414c802f57f6.png)

**Comment by kentcdodds** [comment]
Oh, now that's weird... What is that `@ECHO off` thing 🤔

I'm guessing that's a windows binary thing. I may need to account for that in my new https://npm.im/binode package... Once we figure out the right way to handle that then we should be good.

**Comment by oddig** [comment]
It is for prevent echoing commands at the command prompt, it is the first line in the remix.cmd file

**Comment by kentcdodds** [comment]
Looks like we'll have to figure out how npm executes binaries and either execute them the same way or somehow use npm to execute them. I'm guessing it won't be terribly complicated if we can just use npm to execute them and just update this to do it: https://github.com/kentcdodds/binode/blob/07c94ffdac32fd621b463d5269acf069040f36bf/bin.js#L16

**Comment by kentcdodds** [comment]
Two things:

1. If anyone on a windows machine could give me what the contents of `./node_modules/.bin/remix.CMD` are that would be helpful
2. I'm pretty sure if you updated the script to be `binode --require ./mocks -- npx remix dev` then that would work

But I'd still like to figure out how to avoid the `npx` bit there.

**Comment by kiliman** [comment]
```batch
@ECHO off
GOTO start
:find_dp0
SET dp0=%~dp0
EXIT /b
:start
SETLOCAL
CALL :find_dp0

IF EXIST "%dp0%\node.exe" (
  SET "_prog=%dp0%\node.exe"
) ELSE (
  SET "_prog=node"
  SET PATHEXT=%PATHEXT:;.JS;=;%
)

endLocal & goto #_undefined_# 2>NUL || title %COMSPEC% & "%_prog%"  "%dp0%\..\@remix-run\dev\cli.js" %*
```

**Comment by kentcdodds** [comment]
I think I got it in the latest result of binode. Could you give the latest version a try please?

**Comment by oddig** [comment]
![image](https://user-images.githubusercontent.com/432917/159641257-e0e6fee9-5985-4d65-ab1e-6a776baac280.png)

**Comment by oddig** [comment]
Did a small test here locally:
If I did a join on the nodeargs it worked,

binode/bin.js
```
spawnSync(whichBinPath, binArgs, {
  env: { ...process.env, NODE_OPTIONS: nodeArgs.join(" ") },
  stdio: "inherit",
});

Hope it helps!

**Comment by kentcdodds** [comment]
Ok, I think I finally fixed it. Please try again!

**Comment by kiliman** [comment]
Remix 1.3.3 with latest Indie template works on Windows 11.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/47168/159773453-ccc65f76-6466-49b4-8145-10cfc2420ba1.png">

**Comment by kentcdodds** [comment]
Huzzah! Thanks for your patience all!
