### ISSUE TITLE
Missing Environment Variables when Prisma is removed

### ISSUE THREAD

**Issue by grinkus-adapt** [remix-run/indie-stack#208]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

- Clone [the reproduction repo](https://github.com/grinkus-adapt/prisma-removal-from-indie-stack-repro.git) (`git clone https://github.com/grinkus-adapt/prisma-removal-from-indie-stack-repro.git`)
- Copy `.env.example` as `.env` (`cp .env.example .env`)
- Run `npm run build && npm run start`
- It fails. :exclamation: 
- Run `git show` to check what was changed in the last commit (that should be a single line that comments-out `new PrismaClient()`.
- Run `git reset --hard HEAD^1` to remove the changes from last commit (so that the code line from previous step is not commented-out anymore)
- Run `npm run build && npm run start`
- It doesn't fail. :heavy_check_mark: 

### Expected Behavior

App server probably shouldn't fail if `@prisma/client` is not used.

### Actual Behavior

App server fails when `@prisma/client` is not used because now environment variables from `.env` are missing.

[The invariant checking `process.env.SESSION_SECRET`](https://github.com/grinkus-adapt/prisma-removal-from-indie-stack-repro/blob/main/app/session.server.ts#L5) fails.

---

[This is the line](https://github.com/grinkus-adapt/prisma-removal-from-indie-stack-repro/blob/main/app/session.server.ts#L36):
```ts
// app/session.server.ts

export async function getUser(request: Request) {
  return null;

  /**
   * This is so weird!
   *
   * Here's some unreachable code, but somehow when it is removed the
   * build fails: remove the line after this comment block and run
   * `npm run build && npm run start` to see how. (Before removing it
   * the app builds and starts correctly.)
   */
  new PrismaClient();
}
```

**Comment by mcansh** [comment]
> Hey,
> 
> This is because Prisma handled loading the env file for you. Since you removed that, you'll need to install `dotenv`, and use it in your `entry.server.tsx` file like this:
> 
> ```ts
> import dotenv from "dotenv";
> 
> dotenv.config();
> ```

alternative solution to adding it in code, would be changing the start script to 

`binode --require dotenv/config -- @remix-run/serve:remix-serve build`

**Comment by grinkus-adapt** [comment]
> Hey,
> 
> This is because Prisma handled loading the env file for you. Since you removed that, you'll need to install `dotenv`, and use it in your `entry.server.tsx` file like this:
> 
> ```ts
> import dotenv from "dotenv";
> 
> dotenv.config();
> ```

I can't believe it's that simple. It works. Thank you so much!
