### ISSUE TITLE
macOS : --require,./mocks is not allowed in NODE_OPTIONS

### ISSUE THREAD

**Issue by rphlmr** [remix-run/indie-stack#26]
Hello there,

Since binode https://github.com/remix-run/indie-stack/blob/bfe5ecab176cacd60cbbf001ae504c310c8907ba/package.json#L13 I have an error when launching npm run dev

macOS 12.3
node v16.14.2 

```
> dev:remix
> binode --require ./mocks -- remix dev

node: --require,./mocks is not allowed in NODE_OPTIONS
```

**Comment by mtmeyer** [comment]
Having the same issue with it after just generating with `npx create-remix@latest`.  I've run `npm run setup` (even though I'm pretty sure there's no need to) and am getting the same issue when running `npm run dev`.  
It seems to get stuck at `Rebuilding... Done in 152ms.` and never actually serves the dev server.

**Comment by rphlmr** [comment]
Thanks, it works ;)
