### ISSUE TITLE
bun breaks deploy

### ISSUE THREAD

**Issue by justin-hackin** [remix-run/indie-stack#277]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

just run `bun i` in a fresh template derivation and push it out, you will see the action fail, complaining about lockfile:

```
#10 [production-deps 3/4] ADD package.json package-lock.json .npmrc ./
#10 ERROR: failed to calculate checksum of [REDACTED]: "/package-lock.json": not found

#11 [deps 2/3] ADD package.json package-lock.json .npmrc ./
#11 ERROR: failed to calculate checksum of  [REDACTED]: "/package-lock.json": not found
------
 > [deps 2/3] ADD package.json package-lock.json .npmrc ./:
------
------
 > [production-deps 3/4] ADD package.json package-lock.json .npmrc ./:
------
Error: failed to fetch an image or build from source: error building: failed to solve: failed to compute cache key: failed to calculate checksum of [REDACTED]: "/package-lock.json": not found
Error: Process completed with exit code 1.
```

### Expected Behavior

The deploy is successful

### Actual Behavior

The deploy fails

**Comment by mcansh** [comment]
change `package-lock.json` usages in the dockerfile to bun.lockb and update [npm i](url) usage to `bun i` and it should be good to go

**Comment by justin-hackin** [comment]
Okay I see that the init script detects package manager, whoops, thanks
