### ISSUE TITLE
Error: Invariant failed: SESSION_SECRET must be set

### ISSUE THREAD

**Issue by GaneshSrambikal** [remix-run/indie-stack#286]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

After npx create-remix@latest --template remix-run/indie-stack blog-tutorial

and npm run dev 

we expect a successful running server at 3000 

### Expected Behavior

Mock server running
[remix-serve] http://localhost:3000 (http://172.25.160.1:3000)

![remix-success-server](https://github.com/remix-run/indie-stack/assets/33309469/1f520ea3-e151-4361-bd0e-ad222576035e)

### Actual Behavior

**Error: Invariant failed: SESSION_SECRET must be set**
![remix-error-server](https://github.com/remix-run/indie-stack/assets/33309469/3b97addc-ccdd-45e4-af15-1f52b3827c86)

This is because the repo comes with a **.env.example** file but **.env** is missing.

I have read issue in **[issue#71](https://github.com/remix-run/grunge-stack/issues/71)** in **[grunge-stack](https://github.com/remix-run/grunge-stack)** and this **[comment](https://github.com/remix-run/grunge-stack/issues/71#issuecomment-1683915536)** shares some light. It would be convenient to add a note that instructs to add a .env file after in the [Blog tutorial](https://remix.run/docs/en/main/tutorials/blog) page. 
![remix-env](https://github.com/remix-run/indie-stack/assets/33309469/06564570-d20d-4f85-bb45-26d1a353bc76)

**Comment by machour** [comment]
You missed the setup phase as mentioned in the attached PR.
Closing this issue as it's not actually a bug.
