### ISSUE TITLE
superfly/flyctl-actions/setup-flyctl Github Action error

### ISSUE THREAD

**Issue by bryantabaird** [remix-run/indie-stack#288]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Following the README steps and the getting started docs, unable to deploy the main indie stack to fly.io. I suspect this dependabot PR caused this issue: https://github.com/remix-run/indie-stack/pull/280

### Expected Behavior

Deploy the stack to fly.io

### Actual Behavior

Cannot deploy the stack to fly.io. Here is a screenshot from my github action deploy:
<img width="765" alt="image" src="https://github.com/remix-run/indie-stack/assets/9795404/734f66bf-680f-4cd2-be1a-d944b7362d4e">

Even my IDE doesn't like this version: 
<img width="860" alt="image" src="https://github.com/remix-run/indie-stack/assets/9795404/aa5d8a00-fd56-4c3b-80b0-d293d8d612ff">

**Comment by bryantabaird** [comment]
Also, at this time of writing, the latest release seems to be `1.5`:

https://github.com/superfly/flyctl-actions/releases

**Comment by andrecasal** [comment]
This should be `uses: superfly/flyctl-actions/setup-flyctl@v1`.
