### ISSUE TITLE
Docs don't explain MSW setup, users get console errors looking for mockServiceWorker.js

### ISSUE THREAD

**Issue by petecartwright** [remix-run/indie-stack#291]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

- follow stack setup guide
- run `npm run dev`
- navigate around app
- check terminal console, see 404s for `mockServiceWorker.js`
<img width="946" alt="Screenshot 2024-07-20 at 11 43 10 AM" src="https://github.com/user-attachments/assets/b71ca30d-2d26-4042-82e4-aa880261d94a">

### Expected Behavior

Ideally there should be no 404s in the console

### Actual Behavior

MSW requires users to run `npx msw init public  --save` to create the service worker it uses for mocking. The default `npm run dev` runs with the mock server on, so msw checks for that file on some (most?) http requests.

Adding instructions to run that command to the docs should cover this use case - I'll open a PR soon to do that for discussion.

**Comment by MichaelDeBoey** [comment]
@petecartwright I can't seem to reproduce the problem you're explaining here.

Tagging @kettanaito (the creator/maintainer of MSW) to know if we would need to add the created `public/mockServiceWorker.js` file or not

**Comment by kettanaito** [comment]
Hey, folks! 
You need to run `msw init` if you want to use MSW _in the browser_. To my best knowledge, this stack uses MSW primarily for third-party API mocking during _[integration testing](https://github.com/remix-run/indie-stack/blob/b4d5c9cc0a094bee194b7e15990b2e62dbd0fa17/mocks/index.js#L2)_, which runs in Node.js. Thus, there was never the need to generate the worker script via `msw init`.

You can learn more about using MSW in the browser here: https://mswjs.io/docs/integrations/browser.

**Comment by petecartwright** [comment]
yep, I can't reproduce this now either. :thinking: :thinking: :thinking: I'm 95% sure I did with a new repo at the time I filed this, but ¯\_(ツ)_/¯ 

I could have sworn I found was triggering the browser mocking at the time, but I sure don't see it now.

Sorry for the false alarm, closing this and the PR.

@kettanaito big fan of msw btw!
