### ISSUE TITLE
LiveReload only for development

### ISSUE THREAD

**Issue by mohammedzamakhan** [remix-run/indie-stack#32]
https://github.com/remix-run/indie-stack/blob/f02b3a640589b2802b85b3324ba80ec849f1a2be/app/root.tsx#L46

Probably only need for development environment

**Comment by orion-git** [comment]
Already handled by remix internally [here](https://github.com/remix-run/remix/blob/ae0ab5002000b812c14f8b0a32a3dba10292dbc7/packages/remix-react/components.tsx#L1373)
