### ISSUE TITLE
Login falls back to default 'redirectTo' after faulty credentials

### ISSUE THREAD

**Issue by snaguf** [remix-run/indie-stack#42]
So I did this kinda silly thing and added loader to the Index Route  and called `requireUserId` so that if not logged in browser should redirect straight to `/login`. I also added `redirectTo` parameter to `/dashboard` so after the login is succesful browser should redirect to that route.

```tsx
// app/routes/index.tsx
export const loader: LoaderFunction = async ({ request }) => {
  await requireUserId(request, "/dashboard");
  return json({});
};
``` 

Everything worked just like I thought when given correct credentials right after landing to login (got `404` because no `/dashboard` route found, but redirection happend). But if I first submitted faulty credentials and after that give the correct ones, browser redirected to `/notes` which is used as fallback/default argument in almost every time in the login flow.

I think this is not the way redirection with login should work.

With the help of the `URL` in the browser I figured out that after returning `json<ActionData>...` from `action` in `app/routes/login.tsx`, `searchParams` got destroyed, so in the LoginPage component `redirectTo` falls back to `/notes`.

```tsx
// app/routes/index.tsx
export default function LoginPage() {
  const [searchParams] = useSearchParams();
  const redirectTo = searchParams.get("redirectTo") || "/notes"; // <--- THIS LINE
  const actionData = useActionData() as ActionData;
...
```

I'm not sure where and how this should fixed so that it will not impact some core Remix stuff like `works without JS`. Maybe somwhere in `action` by returning it with errors.

( I also skimmed through the [Jokes App](https://remix.run/docs/en/v1/tutorials/jokes#authentication)  and I think, the issue is present there too. )

**Comment by kentcdodds** [comment]
To be clear, are you saying you see this happen only in the "without JS" case?

**Comment by snaguf** [comment]
No, I did not disable JS. Just don't want the fix to have any effect on that.

**Comment by mcansh** [comment]
i think this is due to `<Form />` not forwarding search params by default requiring you to use 
```ts
import {useLocation} from 'remix'

... other imports

export default function LoginPage() {
let location = useLocation()

... other hooks and such

return <Form action={location.pathname + location.search} />
```

**Comment by kentcdodds** [comment]
I believe this has been fixed.
