### ISSUE TITLE
Could not resolve "remix" (following developer blog tutorial)

### ISSUE THREAD

**Issue by skovy** [remix-run/indie-stack#52]
I was following the developer blog tutorial: https://remix.run/docs/en/v1/tutorials/blog

I ran the setup `npx create-remix --template remix-run/indie-stack blog-tutorial`.

It then recommends adding this code:

```ts
import { json, useLoaderData } from "remix";
```

But an error is thrown:

```
Could not resolve "remix"
```

I noticed this recent commit: https://github.com/remix-run/indie-stack/commit/399001c32fe62dfa50d7610c79d1eef7bbcaa113

So I tried the same change:

```ts
import { json } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
```

And it worked as expected. 

This might only require updating the tutorial since it uses this template? I couldn't find any other documentation related to using `@remix-run/react` and `@remix-run/node` over `remix`?

**Comment by kentcdodds** [comment]
We're in the middle of making this change and haven't updated the docs yet, so I've fixed this here so remix as a package still works. Thanks!
