### ISSUE TITLE
Error: Environment variable not found: DATABASE_URL.

### ISSUE THREAD

**Issue by pavlovtech** [remix-run/indie-stack#54]
I'm getting the error after creating the project: Error: error: Environment variable not found: DATABASE_URL.

OS: MacOS

Steps to reproduce:
1) Run npx create-remix --template remix-run/indie-stack test-proj
2) Run npm run dev
3) Open http://localhost:3000 in the browser

Result:
Remix App Server started at http://localhost:3000 (http://192.168.0.47:3000)
Error: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
 | 
 |   provider = "sqlite"
 |   url      = env("DATABASE_URL")
 |

**Comment by kentcdodds** [comment]
Could you double-check that you have a `.env` file I'm the root of the project? If you don't, please copy/paste the example one.

**Comment by omidantilong** [comment]
I also had this problem just now on a fresh install, and the fix was renaming DATABASE_URL to DB_URL in `schema.prisma` and your `.env`. And the Dockerfile too for completeness I guess.

**Comment by javalion** [comment]
Is there a reason why the provided files include .env.example instead of .env?  For folks that are just trying out the Remix Quickstart locally, the .env.example file needs to be manually renamed in order for the app to start.

**Comment by mcansh** [comment]
it should be happening during `remix init` unless you opt out of installing dependencies https://github.com/remix-run/indie-stack/blob/main/remix.init/index.js#L65

**Comment by javalion** [comment]
Thanks for the update @mcansh.  Reran the example and did see the message above.  Ideally, the .env file would be provided independently from running the remix init since it just contains the environment variables.

**Comment by mcansh** [comment]
> Thanks for the update @mcansh.  Reran the example and did see the message above.  Ideally, the .env file would be provided independently from running the remix init since it just contains the environment variables.  

env shouldn't be committed to source control, but maybe we can make it more explicit that you can also just rename the example

**Comment by erangeles** [comment]
@mcansh can you approve my p.r to update the docs to call this out? https://github.com/remix-run/remix/pull/3990/files As a first time user it was not a great developer experience having Remix break on the first run(no pun intended)
