### ISSUE TITLE
Remix Quickstart: Could not resolve "remix"

### ISSUE THREAD

**Issue by sashapavlov** [remix-run/indie-stack#55]
In the section Loading Data of Quickstart there is following code:

import { json, useLoaderData } from "remix";

After adding it there is an error:

ERROR: Could not resolve "remix"

It seems there is no such package in packages.json. Are remix docs not up to date?

**Comment by kentcdodds** [comment]
Sorry for the trouble. We're moving away from the remix package and soon the docs will be updated. We updated this repo too early.

Thanks for the report!

**Comment by handreistoicescu** [comment]
Hey, @kentcdodds! I got stuck on the tutorial following this error. Could you please elaborate a bit on how to fix this?

Thanks in advance!

**Comment by kentcdodds** [comment]
The tutorial has been updated. You'll need to update those imports:

```js
import { json } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
```

**Comment by handreistoicescu** [comment]
@kentcdodds 

Thanks for looking into this! 

Just a heads-up that [these changes](https://github.com/remix-run/remix/commit/ad0dfa18e0cd7f57a14bd0814f222e737029b84d) to the docs aren't reflected (yet?) in the website build. I'm still seeing the old version, even after refreshing, hard-refreshing or opening in an incognito browser window. Could it be that these changes have not been deployed yet?

| URL I'm using | Screenshot |
| --- | --- |
| https://remix.run/docs/en/v1/tutorials/blog#loading-data | ![Screenshot 2022-04-10 at 15 01 41](https://user-images.githubusercontent.com/29334095/162617167-83702aba-e0c2-4c93-ab06-5c82fbd752f7.png) |

I hope this helps. Thanks for the awesome work on Remix!

**Comment by kentcdodds** [comment]
Thanks. I'll look into it!
