### ISSUE TITLE
`npx create-remix --template remix-run/indie-stack` asks different questions depending on app name

### ISSUE THREAD

**Issue by crcastle** [remix-run/indie-stack#59]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. Run `npx create-remix --template remix-run/indie-stack` and name the app as `my-app` or `asdf`.
2. See "Where do you want to deploy?" question
<img width="1347" alt="CleanShot 2022-04-14 at 14 18 38@2x" src="https://user-images.githubusercontent.com/275734/163478140-bc5e89ef-3c93-4a30-9a7a-7f8d76751e0b.png">
3. <kbd>CTRL</kbd>+C to cancel
4. Again, run `npx create-remix --template remix-run/indie-stack` but this time name the app `create-remix-app-indie-stack`.
5. See "What type of app do you want to create?" question
<img width="929" alt="CleanShot 2022-04-14 at 14 21 39@2x" src="https://user-images.githubusercontent.com/275734/163478850-3fc8b4cd-22d3-4eb0-ae6f-f62f73a4d4aa.png">

### Expected Behavior

I expect the questions I'm asked not to change depending on the name I use for my app.

### Actual Behavior

The questions I'm asked change depending on the name I give my app.

Screen recording:

https://user-images.githubusercontent.com/275734/163479487-13e08ef6-380a-4ac7-80c5-1eb9333ffed8.mp4

System and install Node versions:
```shell
~ 
❯ npx -v
8.1.2

~ 
❯ npm -v
8.1.2

~ 
❯ node -v
v16.13.2

~ 
❯ uname -a
Darwin noodles.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

~ 
❯ sw_vers
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258
```

**Comment by mcansh** [comment]
try `npx create-remix@latest` npm has cached your create-remix so you're stuck using 1.2.3 and not 1.4.0

**Comment by crcastle** [comment]
Using `@latest` produces the same questions and same app directory contents. Apologies for not realizing that I wasn't using the most up-to-date version of `create-remix`.

And thanks for the explanation about the hidden features! Closing this issue.
