### ISSUE TITLE
Setup script runs db seed script twice when using sqlite.

### ISSUE THREAD

**Issue by earlofurl** [remix-run/indie-stack#60]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. Create fresh indie stack project.
2. Run `npm run setup`

### Expected Behavior

1. `prisma migrate dev` runs, syncing database and generating client
2. when migrating is complete, `prisma db seed` runs, seeding the database according to seed.ts

### Actual Behavior

1. `prisma migrate dev` runs, and in addition to syncing db and generating client, it also runs the seed script.
2. `prisma db seed` runs, and fails when it hits a unique constraint because the db has already been seeded
[remixSeedSqliteIssue.txt](https://github.com/remix-run/indie-stack/files/8502519/remixSeedSqliteIssue.txt)
.

**Comment by earlofurl** [comment]
Discord user cev#2144 says that the setup command works as intended when using postgresql, but runs twice when using sqlite.

It is unclear from the [Prisma Docs](https://www.prisma.io/docs/concepts/components/prisma-migrate#create-and-apply-migrations) which behavior is intended.

`migrate dev` says it will generate artifacts, but does not say it's supposed to run the seed command.
The next section, `migrate reset`, does explicitly state that it runs the seed command.

In my case, using sqlite, the problem is effectively fixed by replacing `"setup": "prisma migrate dev" && prisma db seed` with `"setup": "prisma migrate dev"`

However, it sounds like this would not automatically seed the db for users who switch to postgresql.

**Comment by mcansh** [comment]
this doesn't appear to happen in prisma 3.15.2
