### ISSUE TITLE
Oops, remix.init failed when choosing Javascript instead of Typescript

### ISSUE THREAD

**Issue by jan-dh** [remix-run/indie-stack#61]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

Running: `npx create-remix --template remix-run/indie-stack` gives an error when selecting the Javascript option instead of the Typescript option:

```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "data.db" at "file:./data.db?connection_limit=1"

SQLite database data.db created at file:./data.db?connection_limit=1

Applying migration `20220307190657_init`

The following migration(s) have been applied:

migrations/
  └─ 20220307190657_init/
    └─ migration.sql

Your database is now in sync with your schema.

✔ Generated Prisma Client (3.11.1 | library) to ./node_modules/@prisma/client in
 244ms


Running seed command `ts-node --require tsconfig-paths/register prisma/seed.ts` ...
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module './seed.ts'
Require stack:
- /Users/jan/Sites/remix-run/prisma/imaginaryUncacheableRequireRes
```

### Expected Behavior

I'd expect the `seed.ts` being a  `.jsx` file when using the Javascript option. Think this is coming from the `package.json` script:

```
"seed": "ts-node --require tsconfig-paths/register prisma/seed.ts"
```
Think basically the script should be changed to use the `prisma/seed.js` file when using the Javascript option. That file is present.

### Actual Behavior

The `seed.ts` file is not present so the `seed`script fails. There is however a `prisma/seed.js` file available.

**Comment by octokatherine** [comment]
just hit the same error

**Comment by marlonfsolis** [comment]
Is this deployed already? I just got same error.
Project name: blog-tutorial-ce75
And all other dependencies:
```
    "@prisma/client": "^3.14.0",
    "@remix-run/node": "^1.5.1",
    "@remix-run/react": "^1.5.1",
    "@remix-run/serve": "^1.5.1",
    "@remix-run/server-runtime": "^1.5.1",
    "bcryptjs": "^2.4.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "tiny-invariant": "^1.2.0"
```

**Comment by mcansh** [comment]
we're working on the right approach to make this as painless as possible for Stack authors, but the changes required in the meantime are: 
- searching the project for `.ts` and replacing it with `.js` (mostly cypress and package.json)
- update the imports in `prisma/seed.js` to `require`
- might need to update vitest config to https://github.com/remix-run/indie-stack/pull/63/files#diff-eff77a779124ec27f998ab492ebf6e220e2f0029c659df504d06f87b57982713

**Comment by marlonfsolis** [comment]
> 

In my case was in the package.json on prisma section.
`  "prisma": {
    "seed": "ts-node --require tsconfig-paths/register prisma/seed.ts"
  }`
Change seed.ts to seed.js and run the setup script.

**Comment by danielbyun** [comment]
personally had to change from `const bcrypt = require("bcryptjs").default` to not include the `default`

running remix with javascript fyi
