### ISSUE TITLE
Feature request: Include a REMIX_DEV_CLIENT_WS_PORT .env variable to better facilitate proxied remix apps.

### ISSUE THREAD

**Issue by laurencefass** [remix-run/indie-stack#65]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

I am running my remix dev server behind an nginx reverse proxy and I cant find a way to define the public websocket URL in a manner similar to other React SSR frameworks to access the proxied socket port. 

package.json
```
  "scripts": {
     ...,
     "dev": "PORT=3300 run-p dev:*",
     ...
   }
```

remix.config.js (this is ignored so Im using .env variable instead)
```
module.exports = {
  ...
  devServerPort: 3301
};
```

.env file (this appears to supercede devServerPort setting in remix.config.js)
```
REMIX_DEV_SERVER_WS_PORT=3301
```

and I am reverse proxying requests through nginx

and routing the app through nginx
```
server {
    listen 80;
    server_name remix1.syntapse.co.uk;
    location / {
        proxy_pass http://0.0.0.0:3300;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location /socket {
        proxy_pass http://0.0.0.0:3001/browser-sync/socket.io;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
```

Reverse proxying the app works through port 3000 as expected but livereload is not working as socket URL is not compatiably with a reverse proxy. When I load into the browser I see a browser network error:

```
(index):26 WebSocket connection to 'wss://mydomain.com:3301/socket' failed:
```

The inclusion of the port in the client URL wont work for a reverse proxied connection where all requests are generally routed to a single port and re-routed through the reverse proxy. A new env var to allow a port forwarding would be advantageous.

### Expected Behavior

Next JS, CRA and Razzle all provide some means to define the public socket URL for reverse proxied development versions of an app.

### Actual Behavior

A single port specification does not support proxied connections where the client side and server side ports will most likely differ.

**Comment by laurencefass** [comment]
Ive just been loaded up a Vite app  and it solves this very problem by providing an HMR configuration which splits the clientport and serverport to enable proxying. 

https://vitejs.dev/config/#server-hmr

**Comment by kentcdodds** [comment]
Hi @laurencefass,

Sorry for not getting to this sooner. I'd say that this is a good use case for forking the stack and making your own. Proxying an app is not common enough for this stack's audience to include in this stack.
