### ISSUE TITLE
Could not resolve "./styles/tailwind.css"

### ISSUE THREAD

**Issue by thecmsdojo** [remix-run/indie-stack#69]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1. Run "npm run dev"
2. <img width="843" alt="Screen Shot 2022-04-23 at 11 11 45 PM" src="https://user-images.githubusercontent.com/93304188/164959304-5af82c25-6186-4cc6-a004-7431ae905c91.png">

### Expected Behavior

The app should start without an issue

### Actual Behavior

App failed to load
<img width="843" alt="Screen Shot 2022-04-23 at 11 11 45 PM" src="https://user-images.githubusercontent.com/93304188/164959330-a0ac33af-113c-4506-8ee0-170888d134e1.png">

**Comment by thecmsdojo** [comment]
This seems to be fixed by going to line #16 of app/root.tsx and change it from
`import tailwindStylesheetUrl from "./styles/tailwind.css"` to
`import tailwindStylesheetUrl from "tailwindcss/tailwind.css";`

**Comment by machour** [comment]
@thecmsdojo you just need to recompilation again first time.
This is because tailwind (dev:css) & remix (dev:remix) are being ran in a different process, and remix finished first.

You should keep the `import tailwindStylesheetUrl from "./styles/tailwind.css"` statement.
