### ISSUE TITLE
After creating new table, version that was deployed to fly get an error

### ISSUE THREAD

**Issue by bmarvinb** [remix-run/indie-stack#77]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

Deploy fresh app to the stage server, than create new table, and push to dev again, after this will deployed to server, observe the error

### Expected Behavior

Migration work the same as in local environment

### Actual Behavior

Migration in server doesn't work
![image](https://user-images.githubusercontent.com/23120972/166805385-f7bd1837-289c-41dc-a9cd-719df89415c7.png)

**Comment by bmarvinb** [comment]
Fix it by manually run "prisma migrate dev"

**Comment by bmarvinb** [comment]
I think it should be automated

**Comment by mcansh** [comment]
migrations made using `npx prisma migrate` should be ran on app start up https://github.com/remix-run/indie-stack/blob/main/start.sh#L9
