### ISSUE TITLE
Unexpected end of file tsconfig.json

### ISSUE THREAD

**Issue by pegak** [remix-run/indie-stack#83]
### Have you experienced this bug with the latest version of the template?

Yes

### Commands
1. Run `npx create-remix --template remix-run/indie-stack`
2. Choose Typescript
3. Go to the folder
4. Run `npm run dev` pr `npm run build`

### Setup
OS: Windows 11
Node.js: 16.15.0 and 18.1.0
NPM: 8.9.0
Shell: 7.3.0-preview.3

### Expected Behavior

Fully working Remix after setup.

### Actual Behavior

For `npm run build` it fails in the step `build:remix`, `remix build`:
![image](https://user-images.githubusercontent.com/12586960/168495964-7b183076-d560-4c1d-960a-d26d08c6aac0.png)
![image](https://user-images.githubusercontent.com/12586960/168495972-a3403498-1997-459f-b122-f33564948976.png)

For `npm run dev` it fails in **Rebuilding** phase.
![image](https://user-images.githubusercontent.com/12586960/168496041-6ba59cef-22ca-47c1-b74d-37507aafbe56.png)

**Comment by machour** [comment]
Weird, it looks like the `tsconfig.json` file is empty, when it should  not be (https://github.com/remix-run/indie-stack/blob/main/tsconfig.json)

Can you check if that's the case ?

**Comment by pegak** [comment]
It does not look empty, it was my first thought too. I also tried to make it valid (in case of comment is a problem), but nothing seems to work. I even tried different versions of Node.

**Comment by pegak** [comment]
I encountered when working on my template (power-metal-stack) and I thought I broke something, but turns out that it might something much harder to investigate as one week ago my repository was working well and now when I use it as a template it is broken in exact same way as Indie-stack.
I need to dig more, if it is not related to something else (maybe Volta as I use it for node management?).

**Comment by pegak** [comment]
I had! After delete it works. But I don't know how did I create it. :D Thanks!

**Comment by machour** [comment]
Opened an issue about this in https://github.com/remix-run/remix/issues/3210

**Comment by pegak** [comment]
Many thanks!
