### ISSUE TITLE
@sendgrid/mail stopped by mock server development

### ISSUE THREAD

**Issue by asciant** [remix-run/indie-stack#84]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

I'm not experienced enough to understand why, but running in local development stops the `@sendgrid/mail` api from working.

1. Create a remix app using this stack.
2. Install `@sendgrid/mail` from npm.
3. Follow the instructions to setup an API key and verify sender.
4. Use the example provided by SendGrid to send mail in an action on a route.
5. The promise never resolves, the request stays in the `(pending)` state for ever.

If you replace `"dev:remix": "cross-env NODE_ENV=development binode --require ./mocks -- @remix-run/dev:remix dev",` in `package.json` with `"dev:remix": "cross-env NODE_ENV=development remix dev",` it works as expected.

### Expected Behavior

That the mock server would function as it does with other requests, log that the request was made with a message.

### Actual Behavior

The mock server seems to block the requests by `@sendgrid/mail`.

**Comment by benmkramer** [comment]
Ran into it this morning myself, thank you for sharing a workaround. Would be great to have it work and log the request but not pass through to send grid locally though!

**Comment by braginteractive** [comment]
Thank you. I am running the Blues stack and needed to comment out `--require ./mocks ` in `./other/pm2.config.js`
