### ISSUE TITLE
error: Environment variable not found: DATABASE_URL

### ISSUE THREAD

**Issue by AviAvinav** [remix-run/indie-stack#93]
### Have you experienced this bug with the latest version of the template?

Yes

### Steps to Reproduce

1.  Clone this repository or run `npx create-remix --template remix-run/indie-stack`
2.  `yarn dev`

### Expected Behavior

The app should start up without a problem

### Actual Behavior

It seems that it can't pick up the environment variables, though when I was using it for a project that I created yesterday it worked fine. The problem seems to have occurred when I used the template for another project today.

It builds the app at first, but when you open http://localhost:3000 on the browser, it throws the following error:

```
Error: error: Environment variable not found: DATABASE_URL.
  -->  schema.prisma:3
   | 
 2 |   provider = "sqlite"
 3 |   url      = env("DATABASE_URL")
   | 

Validation Error Count: 1
    at Object.loadEngine (C:\Users\Acer\Desktop\Development\remix-projects\streaming-website\node_modules\@prisma\client\runtime\index.js:41175:19)
    at Object.instantiateLibrary (C:\Users\Acer\Desktop\Development\remix-projects\streaming-website\node_modules\@prisma\client\runtime\index.js:41104:5)
    at Object.start (C:\Users\Acer\Desktop\Development\remix-projects\streaming-website\node_modules\@prisma\client\runtime\index.js:41254:5)
fatal error: all goroutines are asleep - deadlock!
```

Also, thanks for creating this wonderful template and the Remix framework, really loved them

**Comment by MichaelDeBoey** [comment]
@AviAvinav Did the install run when setting up the project?

`remix.init` should have been run as part of that, which will make sure `.env` file is setup correctly

**Comment by AviAvinav** [comment]
I did not run it when it asks whether to install packages using npm, but I did do `yarn install` manually.

**Comment by MichaelDeBoey** [comment]
Try running `npx remix init`, this should do the same thing.

**Comment by AviAvinav** [comment]
Thanks for the help! It works now.
