### ISSUE TITLE
Redirect after Login  not working in Firefox 72, 80

### ISSUE THREAD

**Issue by Eddie1O** [remix-run/indie-stack#95]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

`npx create-remix --template remix-run/indie-stack`
`cd ./projectFolder/`
`npm run dev`

go to /login
input credentials and click "Log In"

### Expected Behavior

get redirected to `/notes`

### Actual Behavior

after clicking "Log In" URL in Address Bar changes to `/notes` but browser still displays content of `/login` page

**Comment by mcansh** [comment]
I'm using "Firefox Nightly 103.0a1", but it's redirecting me

**Comment by Eddie1O** [comment]
This issue doesn't occur on versions 90 and above. I'm looking for some explanation or workaround for this bug in versions mentioned in the title.

**Comment by machour** [comment]
This is probably an issue in remix itself: https://github.com/remix-run/remix/issues/776

**Comment by mcansh** [comment]
closing in favor of the issue on the remix repo
