### ISSUE TITLE
missing peer dependencies for `pnpm`

### ISSUE THREAD

**Issue by vovsemenv** [remix-run/indie-stack#97]
### Have you experienced this bug with the latest version of the template?

yes

### Steps to Reproduce

```
npx create-remix --template remix-run/indie-stack blog-tutorial
pnpm i
```

### Expected Behavior

no errors or warnings

### Actual Behavior

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies
.
├─┬ @remix-run/dev
│ └─┬ jscodeshift
│   └── ✕ missing peer @babel/preset-env@^7.1.6
└─┬ msw
  └── ✕ unmet peer typescript@">= 4.2.x <= 4.6.x": found 4.7.3
```

**Comment by MichaelDeBoey** [comment]
Will be fixed by https://github.com/remix-run/remix/pull/3413

**Comment by mcansh** [comment]
fix merged upstream in Remix itself - gonna close this :)
